TEAM_NAME_TO_ABBR = {
    "orlando magic": "ORL",
    "golden state warriors": "GSW",
    "philadelphia 76ers": "PHI",
    "denver nuggets": "DEN",
    "miami heat": "MIA",
    "los angeles lakers": "LAL",
    "boston celtics": "BOS",
    "brooklyn nets": "BKN",
    "milwaukee bucks": "MIL",
    "phoenix suns": "PHX",
    "new orleans pelicans": "NOP",
    "sacramento kings": "SAC",
    "utah jazz": "UTA",
    "oklahoma city thunder": "OKC",
    "memphis grizzlies": "MEM",
    "dallas mavericks": "DAL",
    "san antonio spurs": "SAS",
    "detroit pistons": "DET",
    "indiana pacers": "IND",
    "chicago bulls": "CHI",
    "atlanta hawks": "ATL",
    "charlotte hornets": "CHA",
    "washington wizards": "WAS",
    "new york knicks": "NYK",
    "toronto raptors": "TOR",
    "cleveland cavaliers": "CLE",
    "houston rockets": "HOU",
    "minnesota timberwolves": "MIN",
    "portland trail blazers": "POR",
    "los angeles clippers": "LAC"
}